import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router'
import GlassCard from '../components/GlassCard'
import { listDevices, type DeviceRecord } from '../lib/api'

const missing = '—'
function statusTone(status: string) { const value = status.toLowerCase(); return value.includes('online') || value === 'up' ? '#4ade80' : value.includes('offline') || value === 'down' ? '#ff6b8a' : '#fbbf24' }
function protocol(device: DeviceRecord) { return device.snmp_version ? (device.monitoring_status ? 'ICMP + SNMP' : 'SNMP') : (device.monitoring_status ? 'ICMP' : '—') }

export default function AllDevices() {
  const [devices, setDevices] = useState<DeviceRecord[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [protocolFilter, setProtocolFilter] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { void listDevices().then(setDevices).catch(e => setError(e instanceof Error ? e.message : 'Failed to load devices')).finally(() => setLoading(false)) }, [])
  const filtered = useMemo(() => devices.filter(d => { const text = `${d.hostname} ${d.ip_address} ${d.mac_address ?? ''} ${d.vendor_name ?? d.vendor ?? ''} ${d.model ?? ''}`.toLowerCase(); const p = protocol(d); const normalizedStatus = d.status.toLowerCase(); const isOnline = normalizedStatus.includes('online') || normalizedStatus === 'up'; const isOffline = normalizedStatus.includes('offline') || normalizedStatus === 'down'; return text.includes(query.toLowerCase()) && (status === 'all' || (status === 'online' ? isOnline : status === 'offline' ? isOffline : normalizedStatus === status)) && (protocolFilter === 'all' || p === protocolFilter) }), [devices, query, status, protocolFilter])
  const online = devices.filter(d => d.status.toLowerCase().includes('online') || d.status.toLowerCase() === 'up').length
  const offline = devices.filter(d => d.status.toLowerCase().includes('offline') || d.status.toLowerCase() === 'down').length
  const snmp = devices.filter(d => Boolean(d.snmp_version)).length
  const metricCards = [
    { label: 'TOTAL DEVICES', value: devices.length, active: status === 'all' && protocolFilter === 'all', onClick: () => { setStatus('all'); setProtocolFilter('all') } },
    { label: 'ONLINE', value: online, active: status === 'online' && protocolFilter === 'all', onClick: () => { setStatus('online'); setProtocolFilter('all') } },
    { label: 'OFFLINE', value: offline, active: status === 'offline' && protocolFilter === 'all', onClick: () => { setStatus('offline'); setProtocolFilter('all') } },
    { label: 'SNMP CONFIGURED', value: snmp, active: protocolFilter === 'SNMP', onClick: () => { setStatus('all'); setProtocolFilter('SNMP') } },
  ]
  return <div className="p-4 md:p-6 space-y-5"><header><h1 className="font-display font-bold text-xl md:text-2xl" style={{ color: 'var(--t-text)' }}>ALL DEVICES</h1><p className="font-mono text-xs mt-1" style={{ color: 'var(--t-muted)' }}>Complete inventory of discovered and managed network devices</p></header>
    {error && <div className="rounded-lg p-3 font-mono text-xs" style={{ color: '#ff6b8a', border: '1px solid rgba(255,51,102,.35)' }}>{error}</div>}
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{metricCards.map(card => <GlassCard key={card.label} onClick={card.onClick} role="button" tabIndex={0} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); card.onClick() } }} className="p-4"><div className="font-mono text-[10px]" style={{ color: 'var(--t-muted)' }}>{card.label}</div><div className="font-display text-2xl font-bold mt-2" style={{ color: 'var(--t-text)' }}>{card.value}</div></GlassCard>)}</div>
    <GlassCard className="p-4"><div className="flex flex-col md:flex-row gap-2"><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, IP, MAC, vendor or model" className="flex-1 rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-bg)', color: 'var(--t-text)', border: '1px solid var(--t-border-light)' }}/><select value={status} onChange={e => setStatus(e.target.value)} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-bg)', color: 'var(--t-text)' }}><option value="all">All statuses</option><option value="online">Online</option><option value="offline">Offline</option></select><select value={protocolFilter} onChange={e => setProtocolFilter(e.target.value)} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-bg)', color: 'var(--t-text)' }}><option value="all">All protocols</option><option>ICMP</option><option>SNMP</option><option>ICMP + SNMP</option></select></div></GlassCard>
    <GlassCard><div className="overflow-x-auto"><table className="w-full text-left" style={{ minWidth: 960 }}><thead><tr style={{ borderBottom: '1px solid var(--t-border-light)' }}>{['Device Name','IP Address','MAC Address','Device Type','Vendor / Model','Site','Status','ICMP','SNMP','Last Seen','Action'].map(h => <th key={h} className="px-4 py-3 font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan={11} className="p-10 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>Loading devices…</td></tr> : filtered.map(d => <tr key={d.id} style={{ borderBottom: '1px solid var(--t-border-alpha)' }}><td className="px-4 py-3 font-medium text-sm" style={{ color: 'var(--t-text)' }}>{d.hostname || missing}</td><td className="px-4 py-3 font-mono text-xs">{d.ip_address || missing}</td><td className="px-4 py-3 font-mono text-xs">{d.mac_address || missing}</td><td className="px-4 py-3 text-xs">{d.device_type || missing}</td><td className="px-4 py-3 text-xs">{[d.vendor_name ?? d.vendor, d.model].filter(Boolean).join(' / ') || missing}</td><td className="px-4 py-3 text-xs">{d.site_id ?? missing}</td><td className="px-4 py-3 text-xs" style={{ color: statusTone(d.status) }}>{d.status || 'Unknown'}</td><td className="px-4 py-3 text-xs">{d.monitoring_status ? 'Enabled' : 'Disabled'}</td><td className="px-4 py-3 text-xs">{d.snmp_version ? 'Configured' : 'Not Configured'}</td><td className="px-4 py-3 font-mono text-[10px]">{d.last_seen ? new Date(d.last_seen).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' }) : missing}</td><td className="px-4 py-3"><Link to={`/devices/${d.id}`} className="font-mono text-xs" style={{ color: 'var(--t-accent)' }}>VIEW DETAILS</Link></td></tr>)}{!loading && !filtered.length && <tr><td colSpan={11} className="p-10 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>{devices.length ? 'No devices match your search or filters.' : 'No devices in inventory.'}</td></tr>}</tbody></table></div></GlassCard></div>
}
