import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import GlassCard from '../components/GlassCard'
import { useAuth } from '../components/AuthContext'
import { getAPMDependencies, getAPMOverview, getAPMServiceMetrics, listAPMApplications, listAPMServices, listDeviceOptions, listSites, type APMFilters, type APMOverviewItem, type APMServiceMetric, type SiteRecord } from '../lib/api'

const number = (value: number) => value.toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', hour12: true })
const percent = (value: number) => `${value.toFixed(2)}%`
const milliseconds = (value: number) => `${value.toFixed(1)} ms`

function MetricCard({ label, value, tone = 'var(--t-text)' }: { label: string; value: string; tone?: string }) {
  return <div className="rounded p-3" style={{ background: 'var(--t-bg)', border: '1px solid var(--t-border-alpha)' }}><div className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>{label}</div><div className="font-display font-semibold text-xl mt-1" style={{ color: tone }}>{value}</div></div>
}

function ResponseTrend({ samples }: { samples: APMServiceMetric[] }) {
  if (!samples.length) return <div className="h-36 flex items-center justify-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>No stored service metrics for this time window.</div>
  const max = Math.max(...samples.map(sample => sample.response_time_ms), 1)
  return <div className="h-36 flex items-end gap-1 px-4 pb-4 pt-5">{samples.slice().reverse().map(sample => <div key={sample.observed_at} title={`${new Date(sample.observed_at).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', hour12: true })}: ${milliseconds(sample.response_time_ms)}`} className="flex-1 rounded-t bg-cyan-400/60" style={{ height: `${Math.max(4, sample.response_time_ms / max * 100)}%` }} />)}</div>
}

function OverviewTable({ items }: { items: APMOverviewItem[] }) {
  return <GlassCard className="overflow-hidden"><div className="px-4 py-3" style={{ borderBottom: '1px solid var(--t-border-light)' }}><h2 className="font-display font-semibold text-sm" style={{ color: 'var(--t-text)' }}>Application Health</h2></div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr style={{ color: 'var(--t-muted)' }}>{['Application / Service', 'Requests', 'Response', 'Errors', 'Slow', 'Availability'].map(label => <th key={label} className="px-4 py-2 font-mono text-[10px] uppercase">{label}</th>)}</tr></thead><tbody>{items.length ? items.map(item => <tr key={`${item.application_id}-${item.service_id}`} style={{ borderTop: '1px solid var(--t-border-alpha)' }}><td className="px-4 py-2"><div className="font-mono text-xs" style={{ color: 'var(--t-text)' }}>{item.application_name}</div><div className="font-mono text-[10px]" style={{ color: 'var(--t-muted)' }}>{item.service_name}</div></td><td className="px-4 py-2 font-mono text-xs">{number(item.request_count)}</td><td className="px-4 py-2 font-mono text-xs" style={{ color: '#00d4ff' }}>{milliseconds(item.response_time_ms)}</td><td className="px-4 py-2 font-mono text-xs" style={{ color: item.error_rate > 5 ? '#ff6688' : 'var(--t-muted)' }}>{number(item.error_count)} ({percent(item.error_rate)})</td><td className="px-4 py-2 font-mono text-xs">{number(item.slow_transaction_count)}</td><td className="px-4 py-2 font-mono text-xs" style={{ color: item.availability_percent < 99 ? '#ffb86b' : '#4ade80' }}>{percent(item.availability_percent)}</td></tr>) : <tr><td colSpan={6} className="px-4 py-8 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>No stored APM metrics for these filters.</td></tr>}</tbody></table></div></GlassCard>
}

export default function APM() {
  const { hasPermission } = useAuth()
  const [hours, setHours] = useState(24)
  const [applicationId, setApplicationId] = useState<number | undefined>()
  const [serviceId, setServiceId] = useState<number | undefined>()
  const [deviceId, setDeviceId] = useState<number | undefined>()
  const [siteId, setSiteId] = useState<number | undefined>()
  const filters: APMFilters = { hours, application_id: applicationId, service_id: serviceId, device_id: deviceId, site_id: siteId, page_size: 100 }
  const applications = useQuery({ queryKey: ['apm-applications'], queryFn: listAPMApplications, staleTime: 300_000, enabled: hasPermission('apm:read'), refetchOnWindowFocus: false })
  const services = useQuery({ queryKey: ['apm-services', applicationId], queryFn: () => listAPMServices(applicationId), staleTime: 300_000, enabled: hasPermission('apm:read'), refetchOnWindowFocus: false })
  const devices = useQuery({ queryKey: ['apm-devices'], queryFn: () => listDeviceOptions({ limit: 500 }), staleTime: 300_000, enabled: hasPermission('apm:read'), refetchOnWindowFocus: false })
  const sites = useQuery<SiteRecord[]>({ queryKey: ['apm-sites'], queryFn: listSites, staleTime: 300_000, enabled: hasPermission('apm:read'), refetchOnWindowFocus: false })
  const overview = useQuery({ queryKey: ['apm-overview', filters], queryFn: () => getAPMOverview(filters), staleTime: 30_000, refetchOnWindowFocus: false, refetchOnMount: false, enabled: hasPermission('apm:read') })
  const serviceMetrics = useQuery({ queryKey: ['apm-service-metrics', serviceId, filters], queryFn: () => getAPMServiceMetrics(serviceId!, filters), staleTime: 30_000, refetchOnWindowFocus: false, refetchOnMount: false, enabled: hasPermission('apm:read') && serviceId != null })
  const dependencies = useQuery({ queryKey: ['apm-dependencies', filters], queryFn: () => getAPMDependencies(filters), staleTime: 30_000, refetchOnWindowFocus: false, refetchOnMount: false, enabled: hasPermission('apm:read') })
  const items = overview.data?.items ?? []
  const totalRequests = items.reduce((sum, item) => sum + item.request_count, 0)
  const totalErrors = items.reduce((sum, item) => sum + item.error_count, 0)
  const availability = items.length ? items.reduce((sum, item) => sum + item.availability_percent, 0) / items.length : 0
  const avgResponse = items.length ? items.reduce((sum, item) => sum + item.response_time_ms, 0) / items.length : 0

  if (!hasPermission('apm:read')) return <div className="p-6 font-mono text-sm" style={{ color: 'var(--t-muted)' }}>You do not have permission to view APM.</div>
  if (overview.isError) return <div className="p-6 font-mono text-sm" style={{ color: '#ff6688' }}>Unable to load stored APM metrics. {overview.error instanceof Error ? overview.error.message : 'Request failed.'}</div>

  return <div className="p-4 md:p-6 space-y-5"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h1 className="font-display font-bold text-2xl tracking-widest" style={{ color: 'var(--t-text)' }}>APM / SERVICE HEALTH</h1><p className="font-mono text-xs mt-1" style={{ color: 'var(--t-muted)' }}>Stored application metrics · no automatic polling</p></div><div className="flex flex-wrap gap-2"><select aria-label="Time range" value={hours} onChange={event => setHours(Number(event.target.value))} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-card)', color: 'var(--t-text)', border: '1px solid var(--t-border-alpha)' }}><option value={1}>Last 1 hour</option><option value={24}>Last 24 hours</option><option value={168}>Last 7 days</option><option value={720}>Last 30 days</option></select><select aria-label="Application filter" value={applicationId ?? ''} onChange={event => { setApplicationId(event.target.value ? Number(event.target.value) : undefined); setServiceId(undefined) }} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-card)', color: 'var(--t-text)', border: '1px solid var(--t-border-alpha)' }}><option value="">All applications</option>{applications.data?.map(application => <option key={application.id} value={application.id}>{application.name} ({application.environment})</option>)}</select><select aria-label="Service filter" value={serviceId ?? ''} onChange={event => setServiceId(event.target.value ? Number(event.target.value) : undefined)} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-card)', color: 'var(--t-text)', border: '1px solid var(--t-border-alpha)' }}><option value="">All services</option>{services.data?.map(service => <option key={service.id} value={service.id}>{service.application_name} / {service.name}</option>)}</select><select aria-label="Device filter" value={deviceId ?? ''} onChange={event => setDeviceId(event.target.value ? Number(event.target.value) : undefined)} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-card)', color: 'var(--t-text)', border: '1px solid var(--t-border-alpha)' }}><option value="">All devices</option>{devices.data?.map(device => <option key={device.id} value={device.id}>{device.hostname || device.ip_address}</option>)}</select><select aria-label="Site filter" value={siteId ?? ''} onChange={event => setSiteId(event.target.value ? Number(event.target.value) : undefined)} className="rounded px-3 py-2 font-mono text-xs" style={{ background: 'var(--t-card)', color: 'var(--t-text)', border: '1px solid var(--t-border-alpha)' }}><option value="">All sites</option>{sites.data?.map(site => <option key={site.id} value={site.id}>{site.name}</option>)}</select></div></div>
    <GlassCard><div className="px-4 py-3" style={{ borderBottom: '1px solid var(--t-border-light)' }}><h2 className="font-display font-semibold text-sm" style={{ color: 'var(--t-text)' }}>Health Overview</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 p-4"><MetricCard label="Requests observed" value={number(totalRequests)} /><MetricCard label="Average response" value={milliseconds(avgResponse)} tone="#00d4ff" /><MetricCard label="Errors" value={number(totalErrors)} tone={totalErrors ? '#ff6688' : '#4ade80'} /><MetricCard label="Availability" value={percent(availability)} tone={availability && availability < 99 ? '#ffb86b' : '#4ade80'} /></div></GlassCard>
    <OverviewTable items={items} />
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-4"><GlassCard><div className="px-4 py-3" style={{ borderBottom: '1px solid var(--t-border-light)' }}><h2 className="font-display font-semibold text-sm" style={{ color: 'var(--t-text)' }}>Response Time Trend</h2><p className="font-mono text-[10px] mt-1" style={{ color: 'var(--t-muted)' }}>{serviceId ? 'Selected service historical samples' : 'Select a service to inspect historical samples'}</p></div><ResponseTrend samples={serviceMetrics.data?.items ?? []} /></GlassCard><GlassCard className="overflow-hidden"><div className="px-4 py-3" style={{ borderBottom: '1px solid var(--t-border-light)' }}><h2 className="font-display font-semibold text-sm" style={{ color: 'var(--t-text)' }}>Dependencies</h2></div><div className="overflow-x-auto"><table className="w-full text-left"><thead><tr style={{ color: 'var(--t-muted)' }}>{['Source', 'Target', 'Calls', 'Errors', 'Response'].map(label => <th key={label} className="px-4 py-2 font-mono text-[10px] uppercase">{label}</th>)}</tr></thead><tbody>{dependencies.data?.items?.length ? dependencies.data.items.map(item => <tr key={`${item.source_service_id}-${item.target_name}`} style={{ borderTop: '1px solid var(--t-border-alpha)' }}><td className="px-4 py-2 font-mono text-xs">{item.source_service_name}</td><td className="px-4 py-2 font-mono text-xs">{item.target_name}</td><td className="px-4 py-2 font-mono text-xs">{number(item.call_count)}</td><td className="px-4 py-2 font-mono text-xs" style={{ color: item.error_rate ? '#ff6688' : 'var(--t-muted)' }}>{number(item.error_count)} ({percent(item.error_rate)})</td><td className="px-4 py-2 font-mono text-xs" style={{ color: '#00d4ff' }}>{milliseconds(item.response_time_ms)}</td></tr>) : <tr><td colSpan={5} className="px-4 py-8 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>No stored dependencies for these filters.</td></tr>}</tbody></table></div></GlassCard></div>
  </div>
}
