import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import GlassCard from '../components/GlassCard'
import { useAuth } from '../components/AuthContext'
import { createProblem, getProblem, listIncidents, listProblems, listUsers, linkProblemIncident, updateProblem, type ManagedProblem } from '../lib/api'

const inputStyle = { background: 'var(--t-card)', color: 'var(--t-text)', border: '1px solid var(--t-border-alpha)' }
const categories = ['availability', 'performance', 'security', 'capacity', 'other']
const priorities = ['p1', 'p2', 'p3', 'p4']
const statuses = ['open', 'in_progress', 'known_error', 'resolved', 'closed']

export default function ProblemManagement() {
  const { hasPermission } = useAuth()
  const client = useQueryClient()
  const canRead = hasPermission('problems:read')
  const canWrite = hasPermission('problems:update')
  const [selected, setSelected] = useState<number>()
  const [incidentToLink, setIncidentToLink] = useState('')
  const [createForm, setCreateForm] = useState({ title: '', category: 'availability', priority: 'p3', owner_id: '' })
  const [draft, setDraft] = useState({ title: '', category: 'availability', priority: 'p3', status: 'open', root_cause: '', workaround: '', known_error: '', permanent_fix: '', owner_id: '' })
  const problems = useQuery({ queryKey: ['problems'], queryFn: () => listProblems(), enabled: canRead, staleTime: 30_000, refetchOnWindowFocus: false })
  const detail = useQuery({ queryKey: ['problem', selected], queryFn: () => getProblem(selected!), enabled: canRead && selected != null, staleTime: 30_000, refetchOnWindowFocus: false })
  const users = useQuery({ queryKey: ['problem-owners'], queryFn: listUsers, enabled: canRead && hasPermission('users:read'), staleTime: 30_000, refetchOnWindowFocus: false })
  const incidents = useQuery({ queryKey: ['problem-incidents'], queryFn: () => listIncidents(), enabled: canRead && hasPermission('incidents:read'), staleTime: 30_000, refetchOnWindowFocus: false })
  const item: ManagedProblem | undefined = detail.data ?? problems.data?.items.find(row => row.id === selected)

  useEffect(() => {
    if (!item) return
    setDraft({ title: item.title, category: item.category, priority: item.priority, status: item.status, root_cause: item.root_cause ?? '', workaround: item.workaround ?? '', known_error: item.known_error ?? '', permanent_fix: item.permanent_fix ?? '', owner_id: item.owner_id == null ? '' : String(item.owner_id) })
  }, [item])

  const refresh = () => { client.invalidateQueries({ queryKey: ['problems'] }); client.invalidateQueries({ queryKey: ['problem', selected] }) }
  const create = useMutation({ mutationFn: () => createProblem({ title: createForm.title, category: createForm.category, priority: createForm.priority, owner_id: createForm.owner_id ? Number(createForm.owner_id) : null, incident_ids: [] }), onSuccess: created => { setSelected(created.id); setCreateForm({ ...createForm, title: '' }); refresh() } })
  const update = useMutation({ mutationFn: () => updateProblem(item!.id, { title: draft.title, category: draft.category, priority: draft.priority, status: draft.status, root_cause: draft.root_cause || null, workaround: draft.workaround || null, known_error: draft.known_error || null, permanent_fix: draft.permanent_fix || null, owner_id: draft.owner_id ? Number(draft.owner_id) : null }), onSuccess: refresh })
  const link = useMutation({ mutationFn: () => linkProblemIncident(item!.id, Number(incidentToLink)), onSuccess: () => { setIncidentToLink(''); refresh() } })
  const edit = (key: keyof typeof draft) => draft[key]
  const updateDraft = (key: keyof typeof draft, value: string) => setDraft(current => ({ ...current, [key]: value }))

  if (!canRead) return <div className="p-6 font-mono text-sm" style={{ color: 'var(--t-muted)' }}>You do not have permission to view problem management.</div>
  const linked = new Set(item?.incident_ids ?? [])
  const setCreate = (key: keyof typeof createForm, value: string) => setCreateForm(current => ({ ...current, [key]: value }))
  const textField = (label: string, key: keyof typeof draft, multiline = false) => <label className="block"><span className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>{label}</span>{multiline ? <textarea value={edit(key)} onChange={event => updateDraft(key, event.target.value)} className="mt-1 w-full rounded px-3 py-2 font-mono text-xs min-h-20" style={inputStyle} /> : <input value={edit(key)} onChange={event => updateDraft(key, event.target.value)} className="mt-1 w-full rounded px-3 py-2 font-mono text-xs" style={inputStyle} />}</label>

  return <div className="p-4 md:p-6 space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-display font-bold text-2xl tracking-widest" style={{ color: 'var(--t-text)' }}>PROBLEM MANAGEMENT</h1><p className="font-mono text-xs mt-1" style={{ color: 'var(--t-muted)' }}>Persisted problems, linked incidents and operational lifecycle</p></div>{hasPermission('problems:create') && <div className="flex flex-wrap gap-2"><input aria-label="Problem title" placeholder="Problem title" value={createForm.title} onChange={event => setCreate('title', event.target.value)} className="rounded px-3 py-2 font-mono text-xs" style={inputStyle} /><select aria-label="Problem category" value={createForm.category} onChange={event => setCreate('category', event.target.value)} className="rounded px-3 py-2 font-mono text-xs" style={inputStyle}>{categories.map(value => <option key={value}>{value}</option>)}</select><select aria-label="Problem priority" value={createForm.priority} onChange={event => setCreate('priority', event.target.value)} className="rounded px-3 py-2 font-mono text-xs" style={inputStyle}>{priorities.map(value => <option key={value}>{value}</option>)}</select>{hasPermission('users:read') && <select aria-label="Problem owner" value={createForm.owner_id} onChange={event => setCreate('owner_id', event.target.value)} className="rounded px-3 py-2 font-mono text-xs" style={inputStyle}><option value="">Unassigned</option>{users.data?.filter(user => user.status === 'active').map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select>}<button type="button" onClick={() => create.mutate()} disabled={!createForm.title.trim() || create.isPending} className="rounded px-3 py-2 font-mono text-xs" style={{ background: '#00d4ff', color: '#06111a' }}>Create problem</button></div>}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[minmax(280px,.8fr)_minmax(0,1.4fr)] gap-4"><GlassCard className="overflow-hidden"><div className="px-4 py-3 font-display font-semibold text-sm" style={{ borderBottom: '1px solid var(--t-border-light)' }}>Problems</div>{problems.data?.items.map(row => <button type="button" key={row.id} onClick={() => setSelected(row.id)} className="w-full text-left px-4 py-3" style={{ borderBottom: '1px solid var(--t-border-alpha)', background: row.id === selected ? 'var(--t-bg)' : 'transparent' }}><div className="font-mono text-xs">{row.number} · {row.title}</div><div className="font-mono text-[10px] mt-1" style={{ color: 'var(--t-muted)' }}>{row.category} · {row.priority} · {row.status} · {row.incident_ids.length} incident(s)</div></button>)}{!problems.data?.items.length && <div className="p-6 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>No persisted problems.</div>}</GlassCard>
      <GlassCard>{item ? <div className="space-y-4"><div><h2 className="font-display font-semibold text-lg">{item.number} · {item.title}</h2><div className="font-mono text-xs mt-1" style={{ color: 'var(--t-muted)' }}>{item.category} · {item.priority} · {item.status} · {item.incident_ids.length} related incident(s)</div></div>{canWrite && <><div className="grid gap-3 md:grid-cols-2">{textField('Title', 'title')}<label className="block"><span className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>Category</span><select value={edit('category')} onChange={event => updateDraft('category', event.target.value)} className="mt-1 w-full rounded px-3 py-2 font-mono text-xs" style={inputStyle}>{categories.map(value => <option key={value}>{value}</option>)}</select></label><label className="block"><span className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>Priority</span><select value={edit('priority')} onChange={event => updateDraft('priority', event.target.value)} className="mt-1 w-full rounded px-3 py-2 font-mono text-xs" style={inputStyle}>{priorities.map(value => <option key={value}>{value}</option>)}</select></label><label className="block"><span className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>Status</span><select value={edit('status')} onChange={event => updateDraft('status', event.target.value)} className="mt-1 w-full rounded px-3 py-2 font-mono text-xs" style={inputStyle}>{statuses.map(value => <option key={value}>{value}</option>)}</select></label>{hasPermission('users:read') && <label className="block"><span className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>Owner</span><select value={edit('owner_id')} onChange={event => updateDraft('owner_id', event.target.value)} className="mt-1 w-full rounded px-3 py-2 font-mono text-xs" style={inputStyle}><option value="">Unassigned</option>{users.data?.filter(user => user.status === 'active').map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label>}</div><div className="grid gap-3 md:grid-cols-2">{textField('Root cause', 'root_cause', true)}{textField('Workaround', 'workaround', true)}{textField('Known error', 'known_error', true)}{textField('Permanent fix', 'permanent_fix', true)}</div><button type="button" onClick={() => update.mutate()} disabled={update.isPending || !edit('title').trim()} className="rounded px-3 py-2 font-mono text-xs" style={inputStyle}>Save problem</button></>}
        <div><h3 className="font-display font-semibold text-sm">Related incidents</h3>{canWrite && hasPermission('incidents:read') && <div className="flex gap-2 mt-2"><select aria-label="Incident to link" value={incidentToLink} onChange={event => setIncidentToLink(event.target.value)} className="flex-1 rounded px-3 py-2 font-mono text-xs" style={inputStyle}><option value="">Select persisted incident</option>{incidents.data?.items.filter(incident => !linked.has(incident.id)).map(incident => <option key={incident.id} value={incident.id}>#{incident.id} · {incident.title}</option>)}</select><button type="button" disabled={!incidentToLink || link.isPending} onClick={() => link.mutate()} className="rounded px-3 py-2 font-mono text-xs" style={inputStyle}>Link incident</button></div>}{item.incidents?.length ? item.incidents.map(incident => <div key={incident.id} className="mt-3 rounded p-3" style={{ background: 'var(--t-bg)' }}><div className="font-mono text-xs">Incident #{incident.id} · {incident.title}</div><div className="font-mono text-[10px] mt-1" style={{ color: 'var(--t-muted)' }}>{incident.status} · {incident.priority}</div>{incident.rca ? <div className="font-mono text-[10px] mt-2">RCA: {incident.rca.root_label} ({incident.rca.root_kind}) · {incident.rca.confidence}% confidence</div> : <div className="font-mono text-[10px] mt-2" style={{ color: 'var(--t-muted)' }}>No RCA linked</div>}</div>) : <div className="font-mono text-xs mt-2" style={{ color: 'var(--t-muted)' }}>No incidents linked yet.</div>}</div>
        <div><h3 className="font-display font-semibold text-sm">Audit history</h3>{item.history?.map(row => <div key={row.id} className="mt-2 font-mono text-xs" style={{ color: 'var(--t-muted)' }}>{row.action}{row.field_name ? ` · ${row.field_name}` : ''} · {new Date(row.created_at).toLocaleString()}</div>)}</div></div> : <div className="p-8 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>Select a persisted problem to inspect and manage it.</div>}</GlassCard></div>
  </div>
}
