import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useNavigate } from 'react-router'
import GlassCard from '../components/GlassCard'
import TablePagination from '../components/TablePagination'
import { useAuth } from '../components/AuthContext'
import { confirmDanger, toast } from '../lib/swal'
import {
  cleanupSyslog, createSyslogRule, deleteSyslogRule, setSyslogRuleEnabled,
  invalidateNmsGetCache, listDeviceOptions, listSyslogRecords, listSyslogRules, SYSLOG_SEVERITY_LABELS,
  updateSyslogRule, type DeviceOptionRecord, type SyslogRecord, type SyslogRule, type SyslogRulePayload,
} from '../lib/api'

const inputStyle: React.CSSProperties = { background: 'var(--t-border-light)', border: '1px solid var(--t-border-alpha)', color: 'var(--t-text)', outline: 'none' }
const PAGE_SIZE = 50
const alertSeverities = ['critical', 'high', 'medium', 'warning', 'low']

function value(value: unknown) { return value === null || value === undefined || value === '' ? 'N/A' : String(value) }
function date(valueToFormat: string | null | undefined) { return valueToFormat ? new Date(valueToFormat).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata', hour12: true }) : 'N/A' }
function severityLabel(severity: number | null) { return severity == null ? 'N/A' : SYSLOG_SEVERITY_LABELS[severity] ?? 'N/A' }
function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="block"><span className="font-mono text-[10px] uppercase tracking-wider" style={{ color: 'var(--t-muted)' }}>{label}</span><span className="mt-1 block">{children}</span></label>
}
function SeverityBadge({ severity }: { severity: number | null }) {
  const colors = ['#ff3366', '#ff5f56', '#ff7a45', '#ff9f43', '#f5c542', '#58c7a5', '#48b8ff', '#9aa6b2']
  return <span className="inline-flex rounded px-2 py-0.5 text-[10px] font-mono uppercase" style={{ color: severity == null ? 'var(--t-muted)' : colors[severity] ?? 'var(--t-muted)', border: `1px solid ${severity == null ? 'var(--t-border-alpha)' : colors[severity] ?? 'var(--t-border-alpha)'}` }}>{severityLabel(severity)}</span>
}

function EventModal({ event, onClose, navigate }: { event: SyslogRecord; onClose: () => void; navigate: (path: string) => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4" onClick={onClose}>
    <div className="glass max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl p-5" onClick={e => e.stopPropagation()}>
      <div className="mb-4 flex items-start justify-between gap-3"><div><p className="font-mono text-xs" style={{ color: 'var(--t-accent)' }}>SYSLOG EVENT #{event.id}</p><h2 className="font-display text-xl font-semibold" style={{ color: 'var(--t-text)' }}>{value(event.message).slice(0, 90)}</h2></div><button className="rounded px-3 py-1 font-mono text-xs" style={inputStyle} onClick={onClose}>CLOSE</button></div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {([
          ['Timestamp', date(event.event_timestamp)], ['Received at', date(event.received_at)], ['Source IP', event.source_ip], ['Device', event.device_name ?? (event.device_id ? `Device #${event.device_id}` : null)],
          ['Facility', event.facility], ['Severity', severityLabel(event.severity)], ['Hostname', event.hostname], ['Application', event.application], ['Process ID', event.process_id], ['Message ID', event.message_id], ['Structured data', event.structured_data], ['Interface ID', event.interface_id],
        ] as Array<[string, unknown]>).map(([label, field]) => <div key={label} className="rounded border p-3" style={{ borderColor: 'var(--t-border-alpha)' }}><div className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>{label}</div><div className="mt-1 break-words text-sm" style={{ color: 'var(--t-text)' }}>{value(field)}</div></div>)}
      </div>
      <div className="mt-3 space-y-3"><div><div className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>Message</div><pre className="mt-1 whitespace-pre-wrap break-words rounded border p-3 text-sm" style={{ borderColor: 'var(--t-border-alpha)', color: 'var(--t-text)' }}>{value(event.message)}</pre></div><div><div className="font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>Raw message</div><pre className="mt-1 whitespace-pre-wrap break-words rounded border p-3 text-xs" style={{ borderColor: 'var(--t-border-alpha)', color: 'var(--t-muted)' }}>{value(event.raw_message)}</pre></div></div>
      <div className="mt-4 flex flex-wrap gap-2 border-t pt-4" style={{ borderColor: 'var(--t-border-alpha)' }}>
        {event.alert_id != null ? <button className="rounded px-3 py-2 font-mono text-xs" style={inputStyle} onClick={() => navigate('/alerts')}>ALERT #{event.alert_id}</button> : <span className="font-mono text-xs" style={{ color: 'var(--t-muted)' }}>Alert: N/A</span>}
        {event.incident_id != null ? <button className="rounded px-3 py-2 font-mono text-xs" style={inputStyle} onClick={() => navigate('/incidents')}>INCIDENT #{event.incident_id}</button> : <span className="font-mono text-xs" style={{ color: 'var(--t-muted)' }}>Incident: N/A</span>}
      </div>
    </div>
  </div>
}

function RuleForm({ rule, devices, onDone }: { rule: SyslogRule | null; devices: DeviceOptionRecord[]; onDone: () => void }) {
  const client = useQueryClient()
  const [form, setForm] = useState<SyslogRulePayload>(() => rule ? { name: rule.name, pattern: rule.pattern, min_severity: rule.min_severity, alert_severity: rule.alert_severity, cooldown_seconds: rule.cooldown_seconds, enabled: rule.enabled, device_id: rule.device_id, source_ip: rule.source_ip, hostname: rule.hostname, facility: rule.facility, application: rule.application } : { name: '', pattern: '', min_severity: null, alert_severity: 'warning', cooldown_seconds: 300, enabled: true, device_id: null, source_ip: null, hostname: null, facility: null, application: null })
  const save = useMutation({ mutationFn: () => rule ? updateSyslogRule(rule.id, form) : createSyslogRule(form), onSuccess: () => { toast.success(rule ? 'Rule updated' : 'Rule created'); client.invalidateQueries({ queryKey: ['syslog-rules'] }); onDone() }, onError: e => toast.error(e instanceof Error ? e.message : 'Unable to save rule') })
  const set = (key: keyof SyslogRulePayload, next: unknown) => setForm(current => ({ ...current, [key]: next }))
  return <form className="grid grid-cols-1 gap-3 border-t pt-4 md:grid-cols-3" style={{ borderColor: 'var(--t-border-alpha)' }} onSubmit={e => { e.preventDefault(); if (!form.name.trim() || !form.pattern.trim()) { toast.warning('Rule name and message pattern are required'); return } save.mutate() }}>
    <Field label="Name"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={form.name} onChange={e => set('name', e.target.value)} /></Field>
    <Field label="Message regex / pattern"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={form.pattern} onChange={e => set('pattern', e.target.value)} /></Field>
    <Field label="Minimum severity"><select className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={form.min_severity ?? ''} onChange={e => set('min_severity', e.target.value === '' ? null : Number(e.target.value))}><option value="">Any</option>{SYSLOG_SEVERITY_LABELS.map((item, index) => <option key={item} value={index}>{item}</option>)}</select></Field>
    <Field label="Generated alert severity"><select className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={form.alert_severity} onChange={e => set('alert_severity', e.target.value)}>{alertSeverities.map(item => <option key={item}>{item}</option>)}</select></Field>
    <Field label="Cooldown seconds"><input type="number" min="0" className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={form.cooldown_seconds} onChange={e => set('cooldown_seconds', Number(e.target.value))} /></Field>
    <Field label="Device"><select className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={form.device_id ?? ''} onChange={e => set('device_id', e.target.value === '' ? null : Number(e.target.value))}><option value="">Any device</option>{devices.map(device => <option key={device.id} value={device.id}>{device.hostname} · {device.ip_address}</option>)}</select></Field>
    {([['source_ip', 'Source IP'], ['hostname', 'Hostname'], ['facility', 'Facility'], ['application', 'Application']] as Array<[keyof SyslogRulePayload, string]>).map(([key, label]) => <Field key={key} label={label}><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={String(form[key] ?? '')} onChange={e => set(key, ['facility'].includes(key) ? (e.target.value === '' ? null : Number(e.target.value)) : (e.target.value || null))} /></Field>)}
    <label className="flex items-center gap-2 self-end pb-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e => set('enabled', e.target.checked)} /> Enabled</label>
    <div className="flex gap-2 self-end md:col-span-2"><button disabled={save.isPending} className="rounded px-4 py-2 font-mono text-xs" style={{ ...inputStyle, color: 'var(--t-accent)' }}>{save.isPending ? 'SAVING...' : rule ? 'UPDATE RULE' : 'CREATE RULE'}</button><button type="button" className="rounded px-4 py-2 font-mono text-xs" style={inputStyle} onClick={onDone}>CANCEL</button></div>
  </form>
}

export default function SyslogManagement() {
  const { hasPermission } = useAuth()
  const navigate = useNavigate()
  const client = useQueryClient()
  const [offset, setOffset] = useState(0)
  const [selected, setSelected] = useState<SyslogRecord | null>(null)
  const [editingRule, setEditingRule] = useState<SyslogRule | null | undefined>(undefined)
  const [retentionDays, setRetentionDays] = useState('30')
  const [filters, setFilters] = useState({ start: '', end: '', device_id: '', source_ip: '', hostname: '', severity: '', facility: '', application: '', pattern: '' })
  const devices = useQuery({ queryKey: ['syslog-devices'], queryFn: () => listDeviceOptions({ limit: 500 }), staleTime: 300_000, refetchOnWindowFocus: false })
  const queryFilters = useMemo(() => ({ start: filters.start ? new Date(filters.start).toISOString() : undefined, end: filters.end ? new Date(filters.end).toISOString() : undefined, device_id: filters.device_id ? Number(filters.device_id) : undefined, source_ip: filters.source_ip || undefined, hostname: filters.hostname || undefined, severity: filters.severity === '' ? undefined : Number(filters.severity), facility: filters.facility === '' ? undefined : Number(filters.facility), application: filters.application || undefined, pattern: filters.pattern || undefined, limit: PAGE_SIZE, offset }), [filters, offset])
  const records = useQuery({ queryKey: ['syslog-records', queryFilters], queryFn: () => listSyslogRecords(queryFilters), refetchOnWindowFocus: false, staleTime: 10_000 })
  const rules = useQuery({ queryKey: ['syslog-rules'], queryFn: listSyslogRules, refetchOnWindowFocus: false, enabled: hasPermission('syslog:manage') })
  const toggleRule = useMutation({ mutationFn: ({ id, enabled }: { id: number; enabled: boolean }) => setSyslogRuleEnabled(id, enabled), onSuccess: () => client.invalidateQueries({ queryKey: ['syslog-rules'] }), onError: e => toast.error(e instanceof Error ? e.message : 'Unable to update rule') })
  const removeRule = useMutation({ mutationFn: deleteSyslogRule, onSuccess: () => { toast.success('Rule deleted'); client.invalidateQueries({ queryKey: ['syslog-rules'] }) }, onError: e => toast.error(e instanceof Error ? e.message : 'Unable to delete rule') })
  const cleanup = useMutation({ mutationFn: () => cleanupSyslog(Number(retentionDays)), onSuccess: result => toast.success(`Deleted ${result.deleted} expired events`), onError: e => toast.error(e instanceof Error ? e.message : 'Cleanup failed') })
  const setFilter = (key: keyof typeof filters, next: string) => { setOffset(0); setFilters(current => ({ ...current, [key]: next })) }
  const total = records.data?.total ?? 0
  const page = Math.floor(offset / PAGE_SIZE) + 1
  const pageCount = Math.max(1, Math.ceil(total / PAGE_SIZE))
  const deviceMap = useMemo(() => new Map((devices.data ?? []).map(device => [device.id, device])), [devices.data])
  const displayDevice = (event: SyslogRecord) => event.device_name ?? (event.device_id != null ? deviceMap.get(event.device_id)?.hostname ?? `Device #${event.device_id}` : 'N/A')
  const refresh = () => { invalidateNmsGetCache(); void records.refetch() }
  const deleteConfirmed = async (rule: SyslogRule) => { if (await confirmDanger({ title: `Delete rule "${rule.name}"?`, text: 'This cannot be undone.', confirmText: 'Delete Rule' })) removeRule.mutate(rule.id) }

  return <main className="syslog-page space-y-5 p-4 md:p-6 xl:px-8">
    <div className="syslog-hero flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.2em]" style={{ color: 'var(--t-accent)' }}>Operations / Management</p><h1 className="font-display text-2xl font-semibold" style={{ color: 'var(--t-text)' }}>Syslog Management</h1><p className="mt-1 text-sm" style={{ color: 'var(--t-muted)' }}>Persisted syslog events and correlation rules.</p></div><button onClick={refresh} disabled={records.isFetching} className="rounded px-4 py-2 font-mono text-xs" style={{ ...inputStyle, color: 'var(--t-accent)' }}>{records.isFetching ? 'REFRESHING...' : 'REFRESH'}</button></div>
    <GlassCard className="syslog-filter-card"><div className="syslog-filter-grid grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">
      <Field label="Start"><input type="datetime-local" className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.start} onChange={e => setFilter('start', e.target.value)} /></Field><Field label="End"><input type="datetime-local" className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.end} onChange={e => setFilter('end', e.target.value)} /></Field><Field label="Device"><select className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.device_id} onChange={e => setFilter('device_id', e.target.value)}><option value="">All devices</option>{devices.data?.map(device => <option key={device.id} value={device.id}>{device.hostname}</option>)}</select></Field><Field label="Severity"><select className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.severity} onChange={e => setFilter('severity', e.target.value)}><option value="">All severities</option>{SYSLOG_SEVERITY_LABELS.map((item, index) => <option key={item} value={index}>{item}</option>)}</select></Field><Field label="Facility"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.facility} onChange={e => setFilter('facility', e.target.value)} placeholder="Any facility" /></Field><Field label="Source IP"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.source_ip} onChange={e => setFilter('source_ip', e.target.value)} placeholder="192.0.2.10" /></Field><Field label="Hostname"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.hostname} onChange={e => setFilter('hostname', e.target.value)} /></Field><Field label="Application"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.application} onChange={e => setFilter('application', e.target.value)} /></Field><Field label="Message search"><input className="w-full rounded px-2 py-2 text-sm" style={inputStyle} value={filters.pattern} onChange={e => setFilter('pattern', e.target.value)} placeholder="Search message" /></Field>
    </div></GlassCard>
    <GlassCard className="syslog-table-card"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead><tr className="border-b" style={{ borderColor: 'var(--t-border-alpha)' }}>{['Timestamp', 'Received', 'Device', 'Source / Host', 'Severity', 'Facility', 'Application', 'Message', 'Links'].map(item => <th key={item} className="px-3 py-3 font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>{item}</th>)}</tr></thead><tbody>{records.isLoading ? <tr><td colSpan={9} className="p-8 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>LOADING SYSLOG EVENTS...</td></tr> : records.isError ? <tr><td colSpan={9} className="p-8 text-center text-sm" style={{ color: '#ff6b7a' }}>Unable to load Syslog records.</td></tr> : (records.data?.items ?? []).length === 0 ? <tr><td colSpan={9} className="p-8 text-center font-mono text-xs" style={{ color: 'var(--t-muted)' }}>NO SYSLOG EVENTS MATCH THE CURRENT FILTERS</td></tr> : records.data?.items.map(event => <tr key={event.id} tabIndex={0} className="cursor-pointer border-b transition-colors hover:bg-white/[0.03]" style={{ borderColor: 'var(--t-border-light)' }} onClick={() => setSelected(event)} onKeyDown={e => { if (e.key === 'Enter') setSelected(event) }}><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-text)' }}>{date(event.event_timestamp)}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{date(event.received_at)}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-text)' }}>{displayDevice(event)}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{value(event.source_ip)}<br />{value(event.hostname)}</td><td className="px-3 py-3"><SeverityBadge severity={event.severity} /></td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{value(event.facility)}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{value(event.application)}</td><td className="max-w-sm truncate px-3 py-3 text-xs" style={{ color: 'var(--t-text)' }}>{value(event.message)}</td><td className="px-3 py-3 font-mono text-[10px]" style={{ color: 'var(--t-accent)' }}>{event.alert_id != null ? `A#${event.alert_id}` : 'A/N/A'} {event.incident_id != null ? `I#${event.incident_id}` : 'I/N/A'}</td></tr>)}</tbody></table></div><TablePagination page={page} pageCount={pageCount} pageSize={PAGE_SIZE} startItem={total ? offset + 1 : 0} endItem={Math.min(offset + PAGE_SIZE, total)} totalItems={total} onPageChange={next => setOffset((next - 1) * PAGE_SIZE)} onPageSizeChange={() => setOffset(0)} /></GlassCard>
    {hasPermission('syslog:manage') && <>
      <GlassCard><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-lg font-semibold" style={{ color: 'var(--t-text)' }}>Correlation Rules</h2><p className="text-xs" style={{ color: 'var(--t-muted)' }}>Optional device, source, host, facility, and application conditions are evaluated by the backend.</p></div><button className="rounded px-3 py-2 font-mono text-xs" style={{ ...inputStyle, color: 'var(--t-accent)' }} onClick={() => setEditingRule(null)}>NEW RULE</button></div>{editingRule !== undefined && <RuleForm rule={editingRule} devices={devices.data ?? []} onDone={() => setEditingRule(undefined)} />}{rules.isLoading ? <p className="py-5 font-mono text-xs" style={{ color: 'var(--t-muted)' }}>LOADING RULES...</p> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b" style={{ borderColor: 'var(--t-border-alpha)' }}>{['Name', 'Pattern', 'Conditions', 'Alert severity', 'Cooldown', 'State', 'Actions'].map(item => <th key={item} className="px-3 py-2 font-mono text-[10px] uppercase" style={{ color: 'var(--t-muted)' }}>{item}</th>)}</tr></thead><tbody>{(rules.data ?? []).map(rule => <tr key={rule.id} className="border-b" style={{ borderColor: 'var(--t-border-light)' }}><td className="px-3 py-3 text-sm" style={{ color: 'var(--t-text)' }}>{rule.name}</td><td className="max-w-xs truncate px-3 py-3 font-mono text-xs" style={{ color: 'var(--t-muted)' }}>{rule.pattern}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{[rule.device_id != null && `D#${rule.device_id}`, rule.source_ip, rule.hostname, rule.facility != null && `F${rule.facility}`, rule.application].filter(Boolean).join(' · ') || 'Global'}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{rule.alert_severity}</td><td className="px-3 py-3 text-xs" style={{ color: 'var(--t-muted)' }}>{rule.cooldown_seconds}s</td><td className="px-3 py-3"><span className="font-mono text-[10px]" style={{ color: rule.enabled ? '#57d39b' : 'var(--t-muted)' }}>{rule.enabled ? 'ENABLED' : 'DISABLED'}</span></td><td className="flex gap-2 px-3 py-3"><button className="rounded px-2 py-1 font-mono text-[10px]" style={inputStyle} onClick={() => setEditingRule(rule)}>EDIT</button><button className="rounded px-2 py-1 font-mono text-[10px]" style={inputStyle} onClick={() => toggleRule.mutate({ id: rule.id, enabled: !rule.enabled })}>{rule.enabled ? 'DISABLE' : 'ENABLE'}</button><button className="rounded px-2 py-1 font-mono text-[10px]" style={{ ...inputStyle, color: '#ff6b7a', borderColor: '#ff6b7a66' }} onClick={() => void deleteConfirmed(rule)}>DELETE</button></td></tr>)}</tbody></table></div>}</GlassCard>
      <GlassCard><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-lg font-semibold" style={{ color: 'var(--t-text)' }}>Retention Cleanup</h2><p className="text-xs" style={{ color: 'var(--t-muted)' }}>Uses the existing bounded cleanup endpoint. Automatic retention configuration remains backend-owned.</p></div><div className="flex items-end gap-2"><Field label="Retention days"><input type="number" min="1" className="w-28 rounded px-2 py-2 text-sm" style={inputStyle} value={retentionDays} onChange={e => setRetentionDays(e.target.value)} /></Field><button className="rounded px-3 py-2 font-mono text-xs" style={{ ...inputStyle, color: '#ffb4b4', borderColor: '#ff6b7a66' }} disabled={cleanup.isPending || Number(retentionDays) < 1} onClick={async () => { if (await confirmDanger({ title: 'Run Syslog retention cleanup?', text: `Delete events older than ${retentionDays} days.`, confirmText: 'Run Cleanup' })) cleanup.mutate() }}>{cleanup.isPending ? 'CLEANING...' : 'RUN CLEANUP'}</button></div></div></GlassCard>
    </>}
    {selected && <EventModal event={selected} onClose={() => setSelected(null)} navigate={navigate} />}
  </main>
}
