const dashboard = {
  en: {
    title: 'NETWORK OPERATIONS', live: 'LIVE', subtitle: 'Real device, SNMP and database telemetry · Last updated', loading: 'LOADING…', refresh: 'REFRESH', loadingStored: 'Loading stored monitoring data…',
    totalDevices: 'Total devices', inventory: 'Inventory', online: 'Online', reachable: 'Reachable', offline: 'Offline', unreachable: 'Unreachable', snmpEnabled: 'SNMP enabled', credentialsConfigured: 'Credentials configured', snmpFailed: 'SNMP failed', last24Hours: 'Last 24 hours', criticalAlerts: 'Critical alerts', openAcknowledged: 'Open / acknowledged', warningAlerts: 'Warning alerts', interfacesDown: 'Interfaces down', latestSnmpState: 'Latest SNMP state',
    deviceHealth: 'DEVICE HEALTH', persistedIcmpStatus: 'Persisted ICMP status', availability: 'AVAILABILITY', lastSuccessfulPoll: 'Last successful poll:',
    performance: 'PERFORMANCE', latestNormalizedReadings: 'Latest normalized SNMP readings', unsupportedReading: 'N/A means the collector has not stored a supported reading.',
    snmpMonitoring: 'SNMP MONITORING', pollOutcomes: 'Poll outcomes and collector coverage', successfulPolls: 'Successful polls', failedPolls: 'Failed polls', successfulAttempts: 'Successful attempts', failedAttempts: 'Failed attempts', configuredJobs: 'CONFIGURED POLLING JOBS', unsupportedAttempts: 'UNSUPPORTED ATTEMPTS', noDataAttempts: 'NO DATA', unknownAttempts: 'UNKNOWN', totalAttempts: 'TOTAL ATTEMPTS', activeJobs: 'ACTIVE JOBS', unsupportedOids: 'UNSUPPORTED OIDS', lastSuccess: 'Last success', lastFailure: 'Last failure',
    networkTraffic: 'NETWORK TRAFFIC', storedInterfaceSamples: 'Stored interface samples', rxTraffic: 'RX Traffic', txTraffic: 'TX Traffic', noInterfaceHistory: 'No interface history stored for the selected period',
    topDevicesByTraffic: 'TOP DEVICES BY TRAFFIC', latestInterfaceTotals: 'Latest normalized interface totals', noStoredData: 'No stored data available', deviceFallback: 'Device',
    interfaces: 'INTERFACES', total: 'TOTAL', up: 'UP', down: 'DOWN', errors: 'Errors', drops: 'Drops', alerts: 'ALERTS', activeAlertSeverity: 'Active alert severity',
    networkInformation: 'NETWORK INFORMATION', normalizedTopologyInventory: 'Normalized topology inventory', lldpCdpNeighbors: 'LLDP/CDP neighbors', vlans: 'VLANs', routes: 'Routes', arp: 'ARP', mac: 'MAC', topologyNodes: 'Topology nodes',
    deviceTypes: 'DEVICE TYPES', inventoryClassification: 'Inventory classification', noDeviceTypes: 'No device types classified', recentDevicesActivity: 'RECENT DEVICES / ACTIVITY', lastPersistedState: 'Last persisted device state', device: 'Device', ip: 'IP', type: 'Type', status: 'Status', lastPoll: 'Last poll', noDevices: 'No devices in inventory',
    cpu: 'CPU', memory: 'MEMORY', storage: 'STORAGE', temperature: 'TEMPERATURE', uptime: 'UPTIME', load: 'LOAD', na: 'N/A',
    severity: { critical: 'critical', high: 'high', medium: 'medium', warning: 'warning', low: 'low', info: 'info' },
    health: { online: 'online', offline: 'offline', warning: 'warning', unknown: 'unknown' },
  },
  hi: {
    title: 'नेटवर्क संचालन', live: 'लाइव', subtitle: 'वास्तविक डिवाइस, SNMP और डेटाबेस टेलीमेट्री · अंतिम अपडेट', loading: 'लोड हो रहा है…', refresh: 'रिफ्रेश', loadingStored: 'सहेजा गया मॉनिटरिंग डेटा लोड हो रहा है…',
    totalDevices: 'कुल डिवाइस', inventory: 'इन्वेंटरी', online: 'ऑनलाइन', reachable: 'पहुंच योग्य', offline: 'ऑफलाइन', unreachable: 'पहुंच से बाहर', snmpEnabled: 'SNMP सक्षम', credentialsConfigured: 'क्रेडेंशियल कॉन्फ़िगर हैं', snmpFailed: 'SNMP विफल', last24Hours: 'पिछले 24 घंटे', criticalAlerts: 'गंभीर अलर्ट', openAcknowledged: 'खुले / स्वीकार किए गए', warningAlerts: 'चेतावनी अलर्ट', interfacesDown: 'डाउन इंटरफेस', latestSnmpState: 'नवीनतम SNMP स्थिति',
    deviceHealth: 'डिवाइस स्वास्थ्य', persistedIcmpStatus: 'सहेजी गई ICMP स्थिति', availability: 'उपलब्धता', lastSuccessfulPoll: 'अंतिम सफल पोल:',
    performance: 'प्रदर्शन', latestNormalizedReadings: 'नवीनतम सामान्यीकृत SNMP रीडिंग', unsupportedReading: 'N/A का अर्थ है कि कलेक्टर ने समर्थित रीडिंग सहेजी नहीं है।',
    snmpMonitoring: 'SNMP मॉनिटरिंग', pollOutcomes: 'पोल परिणाम और कलेक्टर कवरेज', successfulPolls: 'सफल पोल', failedPolls: 'विफल पोल', successfulAttempts: 'सफल प्रयास', failedAttempts: 'विफल प्रयास', configuredJobs: 'कॉन्फ़िगर पोलिंग जॉब', unsupportedAttempts: 'असमर्थित प्रयास', noDataAttempts: 'डेटा नहीं', unknownAttempts: 'अज्ञात', totalAttempts: 'कुल प्रयास', activeJobs: 'सक्रिय जॉब', unsupportedOids: 'असमर्थित OID', lastSuccess: 'अंतिम सफलता', lastFailure: 'अंतिम विफलता',
    networkTraffic: 'नेटवर्क ट्रैफिक', storedInterfaceSamples: 'सहेजे गए इंटरफेस सैंपल', rxTraffic: 'RX ट्रैफिक', txTraffic: 'TX ट्रैफिक', noInterfaceHistory: 'चयनित अवधि के लिए इंटरफेस इतिहास उपलब्ध नहीं है',
    topDevicesByTraffic: 'ट्रैफिक के अनुसार प्रमुख डिवाइस', latestInterfaceTotals: 'नवीनतम सामान्यीकृत इंटरफेस कुल', noStoredData: 'सहेजा गया डेटा उपलब्ध नहीं है', deviceFallback: 'डिवाइस',
    interfaces: 'इंटरफेस', total: 'कुल', up: 'अप', down: 'डाउन', errors: 'त्रुटियां', drops: 'ड्रॉप्स', alerts: 'अलर्ट', activeAlertSeverity: 'सक्रिय अलर्ट गंभीरता',
    networkInformation: 'नेटवर्क जानकारी', normalizedTopologyInventory: 'सामान्यीकृत टोपोलॉजी इन्वेंटरी', lldpCdpNeighbors: 'LLDP/CDP पड़ोसी', vlans: 'VLAN', routes: 'रूट', arp: 'ARP', mac: 'MAC', topologyNodes: 'टोपोलॉजी नोड',
    deviceTypes: 'डिवाइस प्रकार', inventoryClassification: 'इन्वेंटरी वर्गीकरण', noDeviceTypes: 'कोई डिवाइस प्रकार वर्गीकृत नहीं', recentDevicesActivity: 'हाल के डिवाइस / गतिविधि', lastPersistedState: 'अंतिम सहेजी गई डिवाइस स्थिति', device: 'डिवाइस', ip: 'IP', type: 'प्रकार', status: 'स्थिति', lastPoll: 'अंतिम पोल', noDevices: 'इन्वेंटरी में कोई डिवाइस नहीं',
    cpu: 'CPU', memory: 'मेमोरी', storage: 'स्टोरेज', temperature: 'तापमान', uptime: 'अपटाइम', load: 'लोड', na: 'N/A',
    severity: { critical: 'गंभीर', high: 'उच्च', medium: 'मध्यम', warning: 'चेतावनी', low: 'कम', info: 'जानकारी' },
    health: { online: 'ऑनलाइन', offline: 'ऑफलाइन', warning: 'चेतावनी', unknown: 'अज्ञात' },
  },
}

const topology = {
  en: {
    title: 'NETWORK TOPOLOGY', subtitle: 'LIVE SNMP · LLDP/CDP CONFIRMED · MAC/ARP PORT INFERENCE', back: 'BACK', updated: 'Updated', notLoaded: 'Not loaded', search: 'Search hostname / IP / MAC', rebuild: 'REBUILD TOPOLOGY', rebuilding: 'REBUILDING…', nodes: 'NODES', links: 'LINKS', confirmed: 'CONFIRMED', inferred: 'INFERRED', macsOnPorts: 'MACs ON PORTS', portGroups: 'PORT GROUPS', autoRefreshOff: 'Auto refresh OFF', liveSyncOn: 'Live sync ON', resetView: 'Reset View', clearSelection: 'Clear Selection', coreConnections: 'CORE-SWITCH CONNECTIONS', noSnapshot: 'No saved topology snapshot available. Use REFRESH to collect one.', zoomIn: 'Zoom in', zoomOut: 'Zoom out', fit: 'FIT', reset: 'RESET', fullscreen: 'FULLSCREEN', exitFullscreen: 'EXIT FULLSCREEN', deviceDetails: 'DEVICE DETAILS', linkDetails: 'LINK DETAILS', topologyLink: 'TOPOLOGY LINK', confirmedLegend: 'LLDP/CDP CONFIRMED', inferredLegend: 'MAC/ARP INFERRED', gatewayPath: 'GATEWAY PATH', clickDetails: 'Click a node or link for details', openSnmpDetails: 'Open SNMP Details', clickConnected: 'Click to open connected device', noLinks: 'No verified or inferred links', databaseDetails: 'DATABASE DETAILS', connections: 'CONNECTIONS', editDevice: 'EDIT DEVICE', close: 'CLOSE', cancel: 'CANCEL', saveChanges: 'SAVE CHANGES', saving: 'SAVING…', noDevices: 'No devices found. Add a device to start monitoring.', searchConnections: 'Filter connected devices / IP / MAC / vendor', unknown: 'UNKNOWN', ipUnknown: 'IP UNKNOWN', macUnknown: 'MAC UNKNOWN', portUnknown: 'PORT UNKNOWN',
  },
  hi: {
    title: 'नेटवर्क टोपोलॉजी', subtitle: 'लाइव SNMP · LLDP/CDP पुष्ट · MAC/ARP पोर्ट अनुमान', back: 'वापस', updated: 'अपडेट', notLoaded: 'लोड नहीं हुआ', search: 'होस्टनेम / IP / MAC खोजें', rebuild: 'टोपोलॉजी रीबिल्ड', rebuilding: 'रीबिल्ड हो रहा है…', nodes: 'नोड', links: 'लिंक', confirmed: 'पुष्ट', inferred: 'अनुमानित', macsOnPorts: 'पोर्ट पर MAC', portGroups: 'पोर्ट समूह', autoRefreshOff: 'ऑटो रिफ्रेश बंद', liveSyncOn: 'लाइव सिंक चालू', resetView: 'व्यू रीसेट', clearSelection: 'चयन साफ़ करें', coreConnections: 'कोर-स्विच कनेक्शन', noSnapshot: 'सहेजा गया टोपोलॉजी स्नैपशॉट उपलब्ध नहीं है। डेटा लेने के लिए रिफ्रेश करें।', zoomIn: 'ज़ूम इन', zoomOut: 'ज़ूम आउट', fit: 'फिट', reset: 'रीसेट', fullscreen: 'फुलस्क्रीन', exitFullscreen: 'फुलस्क्रीन बंद करें', deviceDetails: 'डिवाइस विवरण', linkDetails: 'लिंक विवरण', topologyLink: 'टोपोलॉजी लिंक', confirmedLegend: 'LLDP/CDP पुष्ट', inferredLegend: 'MAC/ARP अनुमानित', gatewayPath: 'गेटवे पथ', clickDetails: 'विवरण के लिए नोड या लिंक चुनें', openSnmpDetails: 'SNMP विवरण खोलें', clickConnected: 'कनेक्टेड डिवाइस खोलने के लिए क्लिक करें', noLinks: 'कोई पुष्ट या अनुमानित लिंक नहीं', databaseDetails: 'डेटाबेस विवरण', connections: 'कनेक्शन', editDevice: 'डिवाइस संपादित करें', close: 'बंद करें', cancel: 'रद्द करें', saveChanges: 'बदलाव सहेजें', saving: 'सहेज रहा है…', noDevices: 'कोई डिवाइस नहीं मिला। मॉनिटरिंग शुरू करने के लिए डिवाइस जोड़ें।', searchConnections: 'कनेक्टेड डिवाइस / IP / MAC / विक्रेता फ़िल्टर करें', unknown: 'अज्ञात', ipUnknown: 'IP अज्ञात', macUnknown: 'MAC अज्ञात', portUnknown: 'पोर्ट अज्ञात',
  },
}

const workflow = {
  en: { manualTitle: 'Manual Topology', manualSubtitle: 'Custom network topology', scanTitle: 'ISP & WAN MONITORING', scanSubtitle: 'Discovery + stored device monitoring flow for your modules', discover: 'DISCOVER DEVICES', discovered: 'DISCOVERED DEVICES', deviceMonitoring: 'DEVICE MONITORING', allDevices: 'ALL DEVICES', totalDevices: 'TOTAL DEVICES', monitored: 'MONITORED', online: 'ONLINE', offline: 'OFFLINE', loadingDevices: 'Loading devices…', noDevices: 'No devices in database. Run a discovery and add devices first.', searchDevice: 'Search device...', searchDevices: 'Search devices...', back: 'BACK', refresh: 'REFRESH', startAll: '▶ START ALL', stopAll: '■ STOP ALL', devices: 'DEVICES', links: 'LINKS', issues: 'ISSUES', connect: 'CONNECT', autoLayout: 'AUTO LAYOUT', fit: 'FIT', snap: 'SNAP', on: 'ON', off: 'OFF', undo: 'UNDO', redo: 'REDO', export: 'EXPORT', showPorts: 'SHOW PORTS', deleteSelected: 'DELETE SELECTED' },
  hi: { manualTitle: 'मैनुअल टोपोलॉजी', manualSubtitle: 'कस्टम नेटवर्क टोपोलॉजी', scanTitle: 'ISP और WAN मॉनिटरिंग', scanSubtitle: 'आपके मॉड्यूल के लिए डिस्कवरी और सहेजे गए डिवाइस मॉनिटरिंग का प्रवाह', discover: 'डिवाइस खोजें', discovered: 'खोजे गए डिवाइस', deviceMonitoring: 'डिवाइस मॉनिटरिंग', allDevices: 'सभी डिवाइस', totalDevices: 'कुल डिवाइस', monitored: 'मॉनिटर किए गए', online: 'ऑनलाइन', offline: 'ऑफलाइन', loadingDevices: 'डिवाइस लोड हो रहे हैं…', noDevices: 'डेटाबेस में कोई डिवाइस नहीं। पहले डिस्कवरी चलाकर डिवाइस जोड़ें।', searchDevice: 'डिवाइस खोजें...', searchDevices: 'डिवाइस खोजें...', back: 'वापस', refresh: 'रिफ्रेश', startAll: '▶ सभी शुरू करें', stopAll: '■ सभी रोकें', devices: 'डिवाइस', links: 'लिंक', issues: 'समस्याएं', connect: 'कनेक्ट', autoLayout: 'ऑटो लेआउट', fit: 'फिट', snap: 'स्नैप', on: 'चालू', off: 'बंद', undo: 'पहले जैसा', redo: 'फिर से करें', export: 'एक्सपोर्ट', showPorts: 'पोर्ट दिखाएं', deleteSelected: 'चयनित हटाएं' },
}

export const translations = {
  en: { loading: 'Loading…', back: 'BACK', systemOperational: 'SYSTEM OPERATIONAL', threatLevel: 'THREAT LEVEL: ELEVATED', language: 'Language', english: 'English', hindi: 'Hindi', dashboard: dashboard.en, topology: topology.en, workflow: workflow.en },
  hi: { loading: 'लोड हो रहा है…', back: 'वापस', systemOperational: 'सिस्टम चालू है', threatLevel: 'खतरे का स्तर: ऊंचा', language: 'भाषा', english: 'अंग्रेज़ी', hindi: 'हिन्दी', dashboard: dashboard.hi, topology: topology.hi, workflow: workflow.hi },
} as const
export type Locale = keyof typeof translations
