import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import ts from 'typescript'

const source = await readFile(new URL('../src/lib/topologyGraphBuilder.ts', import.meta.url), 'utf8')
const runnable = source
  .replace("import type { DeviceRecord } from './api'\n", '')
  .replace("import { agnigateLabel, isAgnigateMac } from './deviceIdentity'\n", "const agnigateLabel = value => value; const isAgnigateMac = () => false;\n")
const js = ts.transpileModule(runnable, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText
const { applyFdbArpEndpointNode, correlateLldpCdpNeighbors, correlatePersistedVerifiedLinks, createLogicalGraphAccumulator, prepareFdbArpCorrelation, remoteFor, resolveFdbArpEndpoint, seedPersistedTopologyNodes } = await import(`data:text/javascript,${encodeURIComponent(js)}`)
const node = id => ({ id, hostname: id, ip: '', mac: '', type: 'switch', status: 'online' })
const link = (from, to, extra = {}) => ({ id: `${from}-${to}`, from, to, source: 'MAC/ARP', confidence: 'INFERRED', ...extra })

{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('A')); assert.equal(graph.getNodes().length, 1) }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'B')); graph.addLink(link('B', 'A')); assert.equal(graph.getLinks().length, 1) }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'A')); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'B')); graph.addLink(link('A', 'B', { source: 'LLDP/CDP', confidence: 'CONFIRMED', localPort: 'Gi1', remotePort: 'Gi2' })); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].confidence, 'CONFIRMED'); assert.equal(graph.getLinks()[0].source, 'LLDP/CDP') }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'B', { source: 'LLDP/CDP', confidence: 'CONFIRMED', localPort: 'Gi1' })); graph.addLink(link('B', 'A')); assert.equal(graph.getLinks()[0].confidence, 'CONFIRMED'); assert.equal(graph.getLinks()[0].localPort, 'Gi1') }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'B', { localPort: 'Gi1', remotePort: 'Gi2' })); graph.addLink(link('B', 'A', { source: 'LLDP/CDP', confidence: 'CONFIRMED' })); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].localPort, 'Gi2'); assert.equal(graph.getLinks()[0].remotePort, 'Gi1') }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'B', { localPort: 'Gi1', remotePort: 'Gi24' })); graph.addLink(link('B', 'A', { source: 'LLDP/CDP', confidence: 'CONFIRMED', localPort: 'Gi24' })); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].localPort, 'Gi24'); assert.equal(graph.getLinks()[0].remotePort, 'Gi1') }
{ const graph = createLogicalGraphAccumulator(); graph.addLink(link('A', 'B')); assert.equal(graph.getLinks()[0].localPort, undefined); assert.equal(graph.getLinks()[0].remotePort, undefined) }
{ const graph = createLogicalGraphAccumulator(); seedPersistedTopologyNodes({ graph, topologyNodes: [{ id: 'p1', ip_address: '10.0.0.2', hostname: 'switch-b' }], inventory: [] }); seedPersistedTopologyNodes({ graph, topologyNodes: [{ id: 'p1', ip_address: '10.0.0.2', hostname: 'switch-b' }], inventory: [] }); assert.equal(graph.getNodes().length, 1) }
{ const graph = createLogicalGraphAccumulator(); seedPersistedTopologyNodes({ graph, topologyNodes: [{ id: 'port-1-Gi1', ip_address: '10.0.0.9' }], inventory: [] }); assert.equal(graph.getNodes().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('managed-1')); seedPersistedTopologyNodes({ graph, topologyNodes: [{ id: 'old', ip_address: '10.0.0.2', hostname: 'switch-b' }], inventory: [{ id: 1, ip_address: '10.0.0.2', hostname: 'switch-b', mac_address: 'aa:bb:cc:dd:ee:ff' }] }); assert.equal(graph.getNodes().length, 2) }
{ const graph = createLogicalGraphAccumulator(); seedPersistedTopologyNodes({ graph, topologyNodes: [{ id: 'old', ip_address: '10.0.0.2' }], inventory: [{ id: 2, ip_address: '10.0.0.2', hostname: '', mac_address: '' }] }); assert.equal(graph.getNodes().length, 1); assert.equal(graph.getNodes()[0].id, '2') }
{ const graph = createLogicalGraphAccumulator(); seedPersistedTopologyNodes({ graph, topologyNodes: [{ id: '', ip_address: '', hostname: '' }], inventory: [] }); assert.equal(graph.getNodes().length, 1); assert.equal(graph.getNodes()[0].id, 'topology-0') }
const lldp = (extra = {}) => ({ localPort: '', remotePort: '', remoteHostname: '', remoteIp: '', remoteMac: '', ...extra })
const collection = (id, neighbors) => ({ device: node(id), macEntries: [], portGroups: [], arpEntries: [], lldpNeighbors: neighbors, routes: [], interfaces: [] })
const inventoryPeer = (id, ip = `10.0.0.${id}`, hostname = `peer-${id}`) => ({ id, ip_address: ip, hostname, mac_address: `aa:bb:cc:dd:ee:${String(id).padStart(2, '0')}` })
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('7')); const peer = remoteFor({ graph, inventory: [{ id: 7, ip_address: '10.0.0.7', hostname: 'peer', mac_address: 'aa:bb:cc:dd:ee:07' }], topologyNodes: [], lldp: lldp({ remoteIp: '10.0.0.7' }), fallbackIndex: 1 }); assert.equal(peer.id, '7') }
{ const graph = createLogicalGraphAccumulator(); const peer = remoteFor({ graph, inventory: [{ id: 8, ip_address: '10.0.0.8', hostname: 'peer', mac_address: 'aa:bb:cc:dd:ee:08' }], topologyNodes: [], lldp: lldp({ remoteIp: '10.0.0.8' }), fallbackIndex: 1 }); assert.equal(peer.id, '8') }
{ const graph = createLogicalGraphAccumulator(); const peer = remoteFor({ graph, inventory: [{ id: 9, ip_address: '10.0.0.9', hostname: 'peer', mac_address: 'aa:bb:cc:dd:ee:09' }], topologyNodes: [], lldp: lldp({ remoteMac: 'aa:bb:cc:dd:ee:09' }), fallbackIndex: 1 }); assert.equal(peer.id, '9') }
{ const graph = createLogicalGraphAccumulator(); const peer = remoteFor({ graph, inventory: [{ id: 10, ip_address: '10.0.0.10', hostname: 'peer', mac_address: 'aa:bb:cc:dd:ee:10' }], topologyNodes: [], lldp: lldp({ remoteHostname: 'peer' }), fallbackIndex: 1 }); assert.equal(peer.id, '10') }
{ const graph = createLogicalGraphAccumulator(); const first = remoteFor({ graph, inventory: [], topologyNodes: [], lldp: lldp({ remoteIp: '10.0.0.99' }), fallbackIndex: 1 }); const second = remoteFor({ graph, inventory: [], topologyNodes: [], lldp: lldp({ remoteIp: '10.0.0.99' }), fallbackIndex: 1 }); assert.equal(first.id, second.id); assert.equal(first.id.startsWith('managed-'), false) }
{ const graph = createLogicalGraphAccumulator(); const peer = remoteFor({ graph, inventory: [{ id: 11, ip_address: '10.0.0.11', hostname: 'unrelated', mac_address: '' }], topologyNodes: [], lldp: lldp({ remoteHostname: 'peer' }), fallbackIndex: 1 }); assert.notEqual(peer.id, 'managed-11') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ local_port: 'Gi1', remote_port: 'Gi2', remote_ip: '10.0.0.2' }])], inventory: [inventoryPeer(2)], topologyNodes: [] }); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].confidence, 'CONFIRMED') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ remote_ip: '10.0.0.2' }]), collection('B', [{ remote_ip: '10.0.0.1' }])], inventory: [{ id: 'A', ip_address: '10.0.0.1', hostname: 'A', mac_address: '' }, { id: 'B', ip_address: '10.0.0.2', hostname: 'B', mac_address: '' }], topologyNodes: [] }); assert.equal(graph.getLinks().length, 1) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ remote_ip: '10.0.0.1' }])], inventory: [{ id: 'A', ip_address: '10.0.0.1', hostname: 'A', mac_address: '' }], topologyNodes: [] }); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ local_port: 'Gi1', remote_port: 'Gi2', remote_ip: '10.0.0.2' }])], inventory: [inventoryPeer(2)], topologyNodes: [] }); const item = graph.getLinks()[0]; assert.equal(item.localPort, 'Gi1'); assert.equal(item.remotePort, 'Gi2'); }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ local_port: 'Gi1', remote_port: 'Gi2', remote_ip: '10.0.0.2' }]), collection('B', [{ local_port: 'Gi2', remote_port: 'Gi1', remote_ip: '10.0.0.1' }])], inventory: [{ id: 'A', ip_address: '10.0.0.1', hostname: 'A', mac_address: '' }, { id: 'B', ip_address: '10.0.0.2', hostname: 'B', mac_address: '' }], topologyNodes: [] }); assert.equal(graph.getLinks().length, 1) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ remote_ip: '10.0.0.2' }])], inventory: [inventoryPeer(2)], topologyNodes: [] }); assert.equal(graph.getLinks()[0].remotePort, '') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ remote_ip: '' }])], inventory: [], topologyNodes: [] }); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); const args = { graph, collections: [collection('A', [{ remote_ip: '10.0.0.2' }])], inventory: [inventoryPeer(2)], topologyNodes: [] }; correlateLldpCdpNeighbors(args); correlateLldpCdpNeighbors(args); assert.equal(graph.getLinks().length, 1) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addLink(link('A', '2')); correlateLldpCdpNeighbors({ graph, collections: [collection('A', [{ remote_ip: '10.0.0.2' }])], inventory: [inventoryPeer(2)], topologyNodes: [] }); assert.equal(graph.getLinks()[0].source, 'LLDP/CDP'); assert.equal(graph.getLinks()[0].confidence, 'CONFIRMED') }
const verified = (extra = {}) => ({ source_node: 'A', target_node: 'B', verified: true, protocol: 'lldp', ...extra })
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified()] }); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].confidence, 'CONFIRMED') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified(), verified({ source_node: 'B', target_node: 'A' })] }); assert.equal(graph.getLinks().length, 1) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified({ target_node: 'A' })] }); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified({ source_port: 'Gi1', target_port: 'Gi2' })] }); assert.equal(graph.getLinks()[0].localPort, 'Gi1'); assert.equal(graph.getLinks()[0].remotePort, 'Gi2') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified({ source_node: 'B', target_node: 'A', source_port: 'Gi2', target_port: 'Gi1' })] }); assert.equal(graph.getLinks()[0].localPort, 'Gi2'); assert.equal(graph.getLinks()[0].remotePort, 'Gi1') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified()] }); assert.equal(graph.getLinks()[0].localPort, ''); assert.equal(graph.getLinks()[0].remotePort, '') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified({ target_node: 'X' })] }); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified({ protocol: 'mac' })] }); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); graph.addLink(link('A', 'B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified()] }); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].confidence, 'CONFIRMED') }
{ const graph = createLogicalGraphAccumulator(); graph.addNode(node('A')); graph.addNode(node('B')); graph.addLink(link('A', 'B')); correlatePersistedVerifiedLinks({ graph, topologyLinks: [verified()] }); assert.equal(graph.getLinks().length, 1); assert.equal(graph.getLinks()[0].source, 'LLDP/CDP') }
const fdbCollection = (macEntries = [], arpEntries = [], portGroups = []) => ({ device: node('A'), macEntries, arpEntries, portGroups, lldpNeighbors: [], routes: [], interfaces: [] })
{ const prepared = prepareFdbArpCorrelation([fdbCollection([{ mac: 'AA-BB-CC-DD-EE-FF', port: 'Gi1' }], [{ mac: 'aa:bb:cc:dd:ee:ff', ip: '10.0.0.5' }])]); assert.equal(prepared.arpByMac.get('aabbccddeeff').ip, '10.0.0.5'); assert.equal(prepared.groupsByPort[0][0].port, 'Gi1') }
{ const prepared = prepareFdbArpCorrelation([fdbCollection([{ mac: 'bad', port: 'Gi1' }, { port: 'Gi2' }])]); assert.equal(prepared.groupsByPort[0].length, 0) }
{ const prepared = prepareFdbArpCorrelation([fdbCollection([{ mac: 'aabbccddeeff', port: 'Gi1' }, { mac: '112233445566', port: 'Gi1' }, { mac: 'aabbccddeeff', port: 'Gi2' }])]); assert.equal(prepared.groupsByPort[0].length, 2); assert.equal(prepared.arpByMac.size, 0) }
{ const graph = createLogicalGraphAccumulator(); const prepared = prepareFdbArpCorrelation([]); assert.equal(prepared.arpByMac.size, 0); assert.equal(prepared.groupsByPort.length, 0); assert.equal(graph.getNodes().length, 0); assert.equal(graph.getLinks().length, 0) }
{ const parent = node('A'); const result = resolveFdbArpEndpoint({ nodes: [parent, { ...node('B'), mac: 'AA:BB:CC:DD:EE:FF' }], parent, groupMacs: ['aa:bb:cc:dd:ee:ff'], ips: ['10.0.0.5'], port: 'Gi1', group: {} }); assert.equal(result.correlatedEndpoint.node.id, 'B'); assert.equal(result.endpointCandidate.ip, '10.0.0.5') }
{ const parent = node('A'); const result = resolveFdbArpEndpoint({ nodes: [parent], parent, groupMacs: ['aa:bb:cc:dd:ee:ff'], ips: [], port: '', group: {} }); assert.equal(result.correlatedEndpoint, undefined); assert.equal(result.endpointCandidate.ip, ''); assert.equal(result.endpointCandidate.port, '') }
{ const graph = createLogicalGraphAccumulator(); const parent = node('A'); const resolution = resolveFdbArpEndpoint({ nodes: [parent], parent, groupMacs: ['aa:bb:cc:dd:ee:ff'], ips: ['10.0.0.5'], port: 'Gi1', group: {} }); const endpoint = applyFdbArpEndpointNode({ graph, resolution, groupMacs: ['aa:bb:cc:dd:ee:ff'], ips: ['10.0.0.5'], port: 'Gi1' }); assert.equal(endpoint.id, 'port-A-1'); assert.equal(graph.getLinks().length, 0) }
{ const graph = createLogicalGraphAccumulator(); const parent = node('A'); const managed = { ...node('B'), mac: 'AA:BB:CC:DD:EE:FF' }; graph.addNode(parent); graph.addNode(managed); const resolution = resolveFdbArpEndpoint({ nodes: graph.getNodes(), parent, groupMacs: ['aa:bb:cc:dd:ee:ff'], ips: ['10.0.0.5'], port: 'Gi1', group: { vlans: [10] } }); const endpoint = applyFdbArpEndpointNode({ graph, resolution, groupMacs: ['aa:bb:cc:dd:ee:ff'], ips: ['10.0.0.5'], port: 'Gi1' }); assert.equal(endpoint.id, 'B'); assert.equal(endpoint.macCount, 1); assert.equal(endpoint.port, 'Gi1'); assert.deepEqual(endpoint.ips, ['10.0.0.5']); assert.deepEqual(endpoint.vlans, [10]) }

console.log('topology accumulator and persisted seeding tests passed')
